### ISSUE TITLE
Issue when installing QGIS-Plugin-CI with the latest release

### ISSUE THREAD

**Issue by Gustry** [opengisch/qgis-plugin-ci#190]
It seems the latest release from this morning has an issue : 

```bash
Run pip install qgis-plugin-ci
Collecting qgis-plugin-ci
  Downloading qgis-plugin-ci-2.5.3.tar.gz (35 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-638oo2x_/qgis-plugin-ci_bde46e383a5240bbadb67c5afe03ac8d/setup.py", line 24, in <module>
          with open(HERE / "requirements/base.txt") as f:
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-638oo2x_/qgis-plugin-ci_bde46e383a5240bbadb67c5afe03ac8d/requirements/base.txt'
      [end of output]
```

It seems linked to #188 @Guts ?

**Comment by Guts** [comment]
Oh ***t!
I'm on it! Sorry for the mess...

**Comment by Guts** [comment]
Okay, got it: that's because we do not package as wheel so pip finds only the tar.gz (sdist) and behaves as it's a simple source archive of the project but without some of missing files.

I'm going to propose a PR to modernize the packaging into a proper wheel.
