### ISSUE TITLE
`pyproject.toml` not used as configuration file

### ISSUE THREAD

**Issue by sluedtke** [opengisch/qgis-plugin-ci#240]
Hi there, 

I encounter the following problem:

If I put the configuration into `pyproject.toml`, the package command fails with:

```
Traceback (most recent call last):
  File "/home/luedtkest/qgis-manager/venv/bin/qgis-plugin-ci", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/luedtkest/qgis-manager/venv/lib/python3.11/site-packages/qgispluginci/cli.py", line 188, in cli
    raise ConfigurationNotFound(
qgispluginci.exceptions.ConfigurationNotFound: .qgis-plugin-ci or setup.cfg with a 'qgis-plugin-ci' section have not been found.

```

The `pyproject.toml` looks like:

```
[qgis-plugin-ci]
plugin_path="qgis_manager"
````

Putting the config into `setup.cfg` works. I use version "2.7.2"  and hope I did not miss anything from the documentation.

Cheers and thanks

**Comment by why-not-try-calmer** [comment]
I'll take a look! Fix or solution in 1-2 days.

**Comment by why-not-try-calmer** [comment]
@sluedtke Which version of the plugin did you install? You can check with `qgis-plugin-ci --version`.

**Comment by sluedtke** [comment]
It's  version  "2.7.2" and I installed via `pip install qgis-plugin-ci`. 

I'll try master to check what's happening there

**Comment by 3nids** [comment]
The docs were published for beta releases, this would explain the expectation.
I have fixed this + releases 2.8.0 which actually offers pyproject.toml config.
@sluedtke  You can give it a new try! https://pypi.org/project/qgis-plugin-ci/2.8.0/

**Comment by sluedtke** [comment]
Excellent, that works .. Thanks a lot!

**Comment by why-not-try-calmer** [comment]
@sluedtke Please notice that we recently adjusted our `pyproject.toml` configuration. If it's not the case already, you'll have to change yours to reflect the change here: https://github.com/opengisch/qgis-plugin-ci/pull/244/files
